#!/bin/bash
# step8_pre2_build_saige_config.sh
# Interactive SAIGE configuration file builder

echo "=========================================="
echo "SAIGE Configuration Builder"
echo "=========================================="
echo ""
echo "This wizard will help you create a SAIGE configuration file."
echo ""

read -p "Output configuration file name [saige_config.txt]: " CONFIG_FILE
CONFIG_FILE="${CONFIG_FILE:-saige_config.txt}"

if [ -f "$CONFIG_FILE" ]; then
    read -p "File exists. Overwrite? (yes/no): " OVERWRITE
    if [ "$OVERWRITE" != "yes" ]; then
        echo "Aborted."
        exit 1
    fi
fi

echo ""
echo "=== Required Parameters ==="
echo ""

read -p "Genotype directory: " GENOTYPE_DIR
read -p "Output directory: " OUTPUT_DIR
read -p "GMMAT model file: " GMMAT_MODEL
read -p "Variance ratio file: " VARIANCE_RATIO

echo ""
read -p "Use separate group file per chromosome? (yes/no) [yes]: " GROUP_BY_CHR
GROUP_BY_CHR="${GROUP_BY_CHR:-yes}"

if [ "$GROUP_BY_CHR" = "yes" ]; then
    read -p "Group files directory: " GROUP_DIR
    GROUP_FILE=""
else
    read -p "Single group file path: " GROUP_FILE
    GROUP_DIR=""
fi

echo ""
echo "=== Format and Processing ==="
echo ""

read -p "Input format (bgen/bfile/pgen/vcf) [bgen]: " INPUT_FORMAT
INPUT_FORMAT="${INPUT_FORMAT:-bgen}"

read -p "Chromosome prefix [chr]: " CHR_PREFIX
CHR_PREFIX="${CHR_PREFIX:-chr}"

read -p "Chromosome padding (auto/yes/no) [auto]: " CHR_PADDING
CHR_PADDING="${CHR_PADDING:-auto}"

read -p "Number of threads [8]: " THREADS
THREADS="${THREADS:-8}"

read -p "Chromosomes to process [1-22]: " CHROMOSOMES
CHROMOSOMES="${CHROMOSOMES:-1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22}"

read -p "Merge chunk results? (yes/no) [yes]: " MERGE_CHUNKS
MERGE_CHUNKS="${MERGE_CHUNKS:-yes}"

if [ "$MERGE_CHUNKS" = "yes" ]; then
    read -p "Keep individual chunk files? (yes/no) [no]: " KEEP_CHUNK_FILES
    KEEP_CHUNK_FILES="${KEEP_CHUNK_FILES:-no}"
else
    KEEP_CHUNK_FILES="yes"
fi

echo ""
echo "=== SAIGE Parameters ==="
echo ""

read -p "Use LOCO? (TRUE/FALSE) [TRUE]: " LOCO
LOCO="${LOCO:-TRUE}"

read -p "Minimum MAF [0]: " minMAF
minMAF="${minMAF:-0}"

read -p "Minimum MAC [1]: " minMAC
minMAC="${minMAC:-1}"

read -p "MAF cutoffs for gene tests [0.0001,0.001,0.01]: " maxMAF_in_groupTest
maxMAF_in_groupTest="${maxMAF_in_groupTest:-0.0001,0.001,0.01}"

read -p "Annotation categories [lof,missense;lof;missense;synonymous]: " annotation_in_groupTest
annotation_in_groupTest="${annotation_in_groupTest:-lof,missense;lof;missense;synonymous}"

read -p "Test type - r.corr (0=SKAT-O, 1=Burden) [0]: " r_corr
r_corr="${r_corr:-0}"

read -p "Use Firth correction? (TRUE/FALSE) [TRUE]: " is_Firth_beta
is_Firth_beta="${is_Firth_beta:-TRUE}"

if [ "$is_Firth_beta" = "TRUE" ]; then
    read -p "P-value cutoff for Firth [0.01]: " pCutoffforFirth
    pCutoffforFirth="${pCutoffforFirth:-0.01}"
else
    pCutoffforFirth=""
fi

echo ""
echo "=== Advanced Options (press Enter to skip) ==="
echo ""

read -p "Is data imputed? (TRUE/FALSE) [FALSE]: " is_imputed_data
is_imputed_data="${is_imputed_data:-FALSE}"

if [ "$is_imputed_data" = "TRUE" ]; then
    read -p "Minimum Info score [0.3]: " minInfo
    minInfo="${minInfo:-0.3}"
    
    read -p "Dosage zero cutoff [0.2]: " dosage_zerod_cutoff
    dosage_zerod_cutoff="${dosage_zerod_cutoff:-0.2}"
    
    read -p "Dosage zero MAC cutoff [10]: " dosage_zerod_MAC_cutoff
    dosage_zerod_MAC_cutoff="${dosage_zerod_MAC_cutoff:-10}"
    
    read -p "Impute method (minor/mean/best_guess) [mean]: " impute_method
    impute_method="${impute_method:-mean}"
else
    minInfo=""
    dosage_zerod_cutoff=""
    dosage_zerod_MAC_cutoff=""
    impute_method=""
fi

read -p "Output marker lists? (TRUE/FALSE) [TRUE]: " is_output_markerList_in_groupTest
is_output_markerList_in_groupTest="${is_output_markerList_in_groupTest:-TRUE}"

read -p "Maximum missing rate [0.15]: " maxMissing
maxMissing="${maxMissing:-0.15}"

echo ""
echo "=== Writing Configuration File ==="
echo ""

cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# SAIGE-GENE Configuration File
# Generated: $(date)
# Generated by: step8_pre2_build_saige_config.sh

#==========================================================================
# REQUIRED PARAMETERS
#==========================================================================

# Input/Output Directories
GENOTYPE_DIR=$GENOTYPE_DIR
OUTPUT_DIR=$OUTPUT_DIR
GMMAT_MODEL=$GMMAT_MODEL
VARIANCE_RATIO=$VARIANCE_RATIO

# Group File Configuration
EOF

if [ "$GROUP_BY_CHR" = "yes" ]; then
    cat >> "$CONFIG_FILE" << EOF
GROUP_FILE_BY_CHR=yes
GROUP_DIR=$GROUP_DIR
EOF
else
    cat >> "$CONFIG_FILE" << EOF
GROUP_FILE=$GROUP_FILE
GROUP_FILE_BY_CHR=no
EOF
fi

cat >> "$CONFIG_FILE" << EOF

#==========================================================================
# FORMAT AND PROCESSING
#==========================================================================

# Input format and file naming
INPUT_FORMAT=$INPUT_FORMAT
CHR_PREFIX=$CHR_PREFIX
CHR_PADDING=$CHR_PADDING

# Processing control
THREADS=$THREADS
CHROMOSOMES=$CHROMOSOMES
CHUNK_PATTERN=chunk

# Result merging
MERGE_CHUNKS=$MERGE_CHUNKS
KEEP_CHUNK_FILES=$KEEP_CHUNK_FILES

#==========================================================================
# SAIGE PARAMETERS
#==========================================================================

# LOCO and filtering
LOCO=$LOCO
minMAF=$minMAF
minMAC=$minMAC
EOF

if [ -n "$maxMissing" ]; then
    echo "maxMissing=$maxMissing" >> "$CONFIG_FILE"
fi

cat >> "$CONFIG_FILE" << EOF

# Gene-based test parameters
maxMAF_in_groupTest=$maxMAF_in_groupTest
annotation_in_groupTest=$annotation_in_groupTest
r.corr=$r_corr

# Effect size estimation
is_Firth_beta=$is_Firth_beta
EOF

if [ -n "$pCutoffforFirth" ]; then
    echo "pCutoffforFirth=$pCutoffforFirth" >> "$CONFIG_FILE"
fi

# Add imputed data parameters if applicable
if [ "$is_imputed_data" = "TRUE" ]; then
    cat >> "$CONFIG_FILE" << EOF

# Imputed data parameters
is_imputed_data=$is_imputed_data
EOF
    [ -n "$minInfo" ] && echo "minInfo=$minInfo" >> "$CONFIG_FILE"
    [ -n "$dosage_zerod_cutoff" ] && echo "dosage_zerod_cutoff=$dosage_zerod_cutoff" >> "$CONFIG_FILE"
    [ -n "$dosage_zerod_MAC_cutoff" ] && echo "dosage_zerod_MAC_cutoff=$dosage_zerod_MAC_cutoff" >> "$CONFIG_FILE"
    [ -n "$impute_method" ] && echo "impute_method=$impute_method" >> "$CONFIG_FILE"
fi

# Add output parameters
cat >> "$CONFIG_FILE" << EOF

# Output control
is_output_markerList_in_groupTest=$is_output_markerList_in_groupTest

#==========================================================================
# ADDITIONAL OPTIONS
#==========================================================================

# Uncomment and modify as needed:
# MACCutoff_to_CollapseUltraRare=10
# minGroupMAC_in_BurdenTest=5
# weights.beta=1,25
# SPAcutoff=2
# is_single_in_groupTest=TRUE
# is_no_weight_in_groupTest=FALSE
# markers_per_chunk=10000
# groups_per_chunk=100

EOF

echo "✓ Configuration file created: $CONFIG_FILE"
echo ""

# Validate the configuration
echo "=== Validating Configuration ==="
echo ""

ERRORS=0

# Check required paths
if [ ! -d "$GENOTYPE_DIR" ]; then
    echo "⚠ WARNING: Genotype directory not found: $GENOTYPE_DIR"
    ERRORS=$((ERRORS + 1))
fi

if [ ! -f "$GMMAT_MODEL" ]; then
    echo "⚠ WARNING: GMMAT model file not found: $GMMAT_MODEL"
    ERRORS=$((ERRORS + 1))
fi

if [ ! -f "$VARIANCE_RATIO" ]; then
    echo "⚠ WARNING: Variance ratio file not found: $VARIANCE_RATIO"
    ERRORS=$((ERRORS + 1))
fi

if [ "$GROUP_BY_CHR" = "yes" ]; then
    if [ ! -d "$GROUP_DIR" ]; then
        echo "⚠ WARNING: Group directory not found: $GROUP_DIR"
        ERRORS=$((ERRORS + 1))
    fi
else
    if [ ! -f "$GROUP_FILE" ]; then
        echo "⚠ WARNING: Group file not found: $GROUP_FILE"
        ERRORS=$((ERRORS + 1))
    fi
fi

if [ $ERRORS -eq 0 ]; then
    echo "✓ Basic validation passed"
    echo ""
    echo "To run full validation:"
    echo "  ./validate_saige_config.sh $CONFIG_FILE"
    echo ""
    echo "To run SAIGE analysis:"
    echo "  ./step8_run_saige_gene_tests.sh $CONFIG_FILE"
else
    echo ""
    echo "⚠ Found $ERRORS warnings"
    echo "  Please check paths before running analysis"
    echo ""
    echo "To validate configuration:"
    echo "  ./validate_saige_config.sh $CONFIG_FILE"
fi

echo ""
echo "Configuration file contents:"
echo "=========================================="
cat "$CONFIG_FILE"
echo "=========================================="

exit 0
